// Dictionnaire trilingue des libellés d'interface (côté invités).
// L'espace organisateurs est en français uniquement (v1).

export const dict = {
  fr: {
    nav: {
      home: "Accueil",
      rsvp: "RSVP",
      programme: "Programme",
      spetses: "Spetses",
      story: "Notre histoire",
      news: "Actualités",
      contact: "Contact",
    },
    home: {
      welcome: "Bienvenue",
      intro: "On se marie à Spetses, et on veut vous avoir avec nous ! Tout ce qu'il faut savoir est ici : le programme, l'île, et surtout… votre réponse.",
      countdown: "jours avant le grand jour",
      cta: "Répondre à l'invitation",
      ctaDone: "Voir / modifier ma réponse",
    },
    rsvp: {
      title: "Votre réponse",
      deadline: "Vous pouvez modifier votre réponse à tout moment jusqu'au",
      closed: "La date limite de réponse est passée. Contactez-nous directement pour tout changement.",
      attending: "Est-ce que vous venez ?",
      yes: "Oui, on sera là ! 🎉",
      no: "Non, on ne pourra pas venir 😢",
      emailLabel: "Votre email (pour vous tenir au courant)",
      emailHint: "On l'utilise uniquement pour les infos du mariage.",
      participants: "Qui vient ?",
      addParticipant: "Ajouter une personne",
      name: "Prénom et nom",
      adult: "Adulte",
      child: "Enfant",
      age: "Âge",
      diet: "Alimentation",
      dietNone: "Rien à signaler",
      dietVeg: "Végétarien / végétalien",
      dietAllergy: "Allergie grave",
      dietNote: "Précisez l'allergie",
      events: "Présent·e à…",
      logistics: "Vos plans (pour nous aider à nous organiser)",
      logisticsHint: "Ces infos nous donnent juste une idée d'ensemble — elles n'engagent personne, ni vous ni nous, et ne valent pas réservation.",
      arrival: "Date d'arrivée",
      departure: "Date de départ",
      transport: "Comment venez-vous ?",
      tPlane: "Avion (via Athènes)",
      tFerry: "Ferry",
      tCar: "Voiture + bateau-taxi",
      tOther: "Autre / pas encore décidé",
      accommodation: "Où logez-vous ?",
      aBooked: "Hébergement réservé",
      aSearching: "En recherche",
      aHosted: "Logé·e par les mariés / famille",
      aUnknown: "Pas encore décidé",
      notes: "Un mot pour nous ? (optionnel)",
      save: "Enregistrer ma réponse",
      saved: "Réponse enregistrée, merci ! Vous pouvez revenir la modifier quand vous voulez.",
      noMsg: "On est tristes, mais merci de nous avoir prévenus. Si vos plans changent, revenez modifier votre réponse !",
    },
    programme: {
      title: "Le programme",
      intro: "Quatre jours de fête. Les lieux et horaires précis seront révélés ici quelques semaines avant — gardez l'œil ouvert.",
      detailsSoon: "Lieu & détails bientôt",
    },
    news: {
      title: "Actualités",
      intro: "Les dernières nouvelles des préparatifs, nos rappels et quelques photos.",
      wallSoon: "📸 Bientôt : un mur de photos où vous pourrez poster les vôtres (avec notre validation avant publication).",
    },
    contact: {
      title: "Une question ?",
      intro: "Écrivez-nous, on répond vite. Et quelques semaines avant le mariage, le lien du groupe WhatsApp apparaîtra ici.",
      name: "Votre nom",
      email: "Votre email",
      message: "Votre message",
      send: "Envoyer",
      sent: "Message envoyé, merci ! On revient vers vous rapidement.",
      whatsappSoon: "Le groupe WhatsApp « sur place » ouvrira quelques semaines avant le mariage.",
      whatsappJoin: "Rejoindre le groupe WhatsApp",
    },
    common: {
      until: "jusqu'au",
      backHome: "Retour à l'accueil",
    },
  },

  en: {
    nav: {
      home: "Home",
      rsvp: "RSVP",
      programme: "Programme",
      spetses: "Spetses",
      story: "Our story",
      news: "News",
      contact: "Contact",
    },
    home: {
      welcome: "Welcome",
      intro: "We're getting married in Spetses, and we want you there! Everything you need is here: the programme, the island, and above all… your answer.",
      countdown: "days until the big day",
      cta: "Reply to the invitation",
      ctaDone: "View / edit my reply",
    },
    rsvp: {
      title: "Your reply",
      deadline: "You can edit your reply anytime until",
      closed: "The reply deadline has passed. Contact us directly for any change.",
      attending: "Are you coming?",
      yes: "Yes, we'll be there! 🎉",
      no: "No, we can't make it 😢",
      emailLabel: "Your email (to keep you posted)",
      emailHint: "Used only for wedding updates.",
      participants: "Who's coming?",
      addParticipant: "Add a person",
      name: "First and last name",
      adult: "Adult",
      child: "Child",
      age: "Age",
      diet: "Diet",
      dietNone: "Nothing to report",
      dietVeg: "Vegetarian / vegan",
      dietAllergy: "Serious allergy",
      dietNote: "Specify the allergy",
      events: "Attending…",
      logistics: "Your plans (to help us organise)",
      logisticsHint: "This just gives us a general picture — it commits no one, you or us, and is not a booking.",
      arrival: "Arrival date",
      departure: "Departure date",
      transport: "How are you coming?",
      tPlane: "Plane (via Athens)",
      tFerry: "Ferry",
      tCar: "Car + water taxi",
      tOther: "Other / not decided yet",
      accommodation: "Where are you staying?",
      aBooked: "Accommodation booked",
      aSearching: "Still looking",
      aHosted: "Hosted by the couple / family",
      aUnknown: "Not decided yet",
      notes: "A word for us? (optional)",
      save: "Save my reply",
      saved: "Reply saved, thank you! You can come back and edit it anytime.",
      noMsg: "We're sad, but thanks for letting us know. If your plans change, come back and edit your reply!",
    },
    programme: {
      title: "The programme",
      intro: "Four days of celebration. Exact venues and times will be revealed here a few weeks before — stay tuned.",
      detailsSoon: "Venue & details soon",
    },
    news: {
      title: "News",
      intro: "The latest from the preparations, our reminders and a few photos.",
      wallSoon: "📸 Coming soon: a photo wall where you can post yours (with our approval before publishing).",
    },
    contact: {
      title: "A question?",
      intro: "Write to us, we answer fast. A few weeks before the wedding, the WhatsApp group link will appear here.",
      name: "Your name",
      email: "Your email",
      message: "Your message",
      send: "Send",
      sent: "Message sent, thank you! We'll get back to you soon.",
      whatsappSoon: "The on-site WhatsApp group will open a few weeks before the wedding.",
      whatsappJoin: "Join the WhatsApp group",
    },
    common: {
      until: "until",
      backHome: "Back to home",
    },
  },

  el: {
    nav: {
      home: "Αρχική",
      rsvp: "RSVP",
      programme: "Πρόγραμμα",
      spetses: "Σπέτσες",
      story: "Η ιστορία μας",
      news: "Νέα",
      contact: "Επικοινωνία",
    },
    home: {
      welcome: "Καλώς ήρθατε",
      intro: "Παντρευόμαστε στις Σπέτσες και σας θέλουμε μαζί μας! Εδώ θα βρείτε όλα όσα χρειάζεστε: το πρόγραμμα, το νησί και κυρίως… την απάντησή σας.",
      countdown: "ημέρες μέχρι τη μεγάλη μέρα",
      cta: "Απαντήστε στην πρόσκληση",
      ctaDone: "Δείτε / αλλάξτε την απάντησή μου",
    },
    rsvp: {
      title: "Η απάντησή σας",
      deadline: "Μπορείτε να αλλάξετε την απάντησή σας οποτεδήποτε μέχρι",
      closed: "Η προθεσμία απάντησης πέρασε. Επικοινωνήστε μαζί μας για οποιαδήποτε αλλαγή.",
      attending: "Θα έρθετε;",
      yes: "Ναι, θα είμαστε εκεί! 🎉",
      no: "Όχι, δεν θα τα καταφέρουμε 😢",
      emailLabel: "Το email σας (για να σας ενημερώνουμε)",
      emailHint: "Το χρησιμοποιούμε μόνο για νέα του γάμου.",
      participants: "Ποιοι έρχονται;",
      addParticipant: "Προσθήκη ατόμου",
      name: "Ονοματεπώνυμο",
      adult: "Ενήλικας",
      child: "Παιδί",
      age: "Ηλικία",
      diet: "Διατροφή",
      dietNone: "Τίποτα ιδιαίτερο",
      dietVeg: "Χορτοφάγος / vegan",
      dietAllergy: "Σοβαρή αλλεργία",
      dietNote: "Περιγράψτε την αλλεργία",
      events: "Παρών/ούσα σε…",
      logistics: "Τα σχέδιά σας (για να οργανωθούμε)",
      logisticsHint: "Οι πληροφορίες αυτές μας δίνουν απλώς μια γενική εικόνα — δεν δεσμεύουν κανέναν και δεν αποτελούν κράτηση.",
      arrival: "Ημερομηνία άφιξης",
      departure: "Ημερομηνία αναχώρησης",
      transport: "Πώς θα έρθετε;",
      tPlane: "Αεροπλάνο (μέσω Αθήνας)",
      tFerry: "Πλοίο",
      tCar: "Αυτοκίνητο + θαλάσσιο ταξί",
      tOther: "Άλλο / δεν έχει αποφασιστεί",
      accommodation: "Πού θα μείνετε;",
      aBooked: "Κατάλυμα κλεισμένο",
      aSearching: "Ψάχνουμε ακόμα",
      aHosted: "Φιλοξενούμενοι από το ζευγάρι / την οικογένεια",
      aUnknown: "Δεν έχει αποφασιστεί",
      notes: "Ένα μήνυμα για εμάς; (προαιρετικό)",
      save: "Αποθήκευση απάντησης",
      saved: "Η απάντηση αποθηκεύτηκε, ευχαριστούμε! Μπορείτε να την αλλάξετε όποτε θέλετε.",
      noMsg: "Λυπόμαστε, αλλά ευχαριστούμε που μας ενημερώσατε. Αν αλλάξουν τα σχέδιά σας, ελάτε να αλλάξετε την απάντησή σας!",
    },
    programme: {
      title: "Το πρόγραμμα",
      intro: "Τέσσερις ημέρες γιορτής. Οι ακριβείς τοποθεσίες και ώρες θα ανακοινωθούν εδώ λίγες εβδομάδες πριν.",
      detailsSoon: "Τοποθεσία & λεπτομέρειες σύντομα",
    },
    news: {
      title: "Νέα",
      intro: "Τα τελευταία νέα των προετοιμασιών, υπενθυμίσεις και μερικές φωτογραφίες.",
      wallSoon: "📸 Σύντομα: ένας τοίχος φωτογραφιών όπου θα ανεβάζετε τις δικές σας (με έγκριση πριν τη δημοσίευση).",
    },
    contact: {
      title: "Έχετε ερωτήσεις;",
      intro: "Γράψτε μας, απαντάμε γρήγορα. Λίγες εβδομάδες πριν τον γάμο, εδώ θα εμφανιστεί ο σύνδεσμος της ομάδας WhatsApp.",
      name: "Το όνομά σας",
      email: "Το email σας",
      message: "Το μήνυμά σας",
      send: "Αποστολή",
      sent: "Το μήνυμα στάλθηκε, ευχαριστούμε! Θα σας απαντήσουμε σύντομα.",
      whatsappSoon: "Η ομάδα WhatsApp θα ανοίξει λίγες εβδομάδες πριν τον γάμο.",
      whatsappJoin: "Μπείτε στην ομάδα WhatsApp",
    },
    common: {
      until: "μέχρι",
      backHome: "Πίσω στην αρχική",
    },
  },
};
