// Dictionnaire trilingue des libellés d'interface (côté invités).
// L'espace organisateurs est en français uniquement (v1).

export const dict = {
  fr: {
    nav: {
      home: "Accueil",
      rsvp: "RSVP",
      programme: "Programme",
      spetses: "Spetses",
      story: "Notre histoire",
      news: "Actualités",
      contact: "Contact",
    },
    home: {
      welcome: "Bienvenue",
      intro: "On se marie à Spetses, et on veut vous avoir avec nous ! Tout ce qu'il faut savoir est ici : le programme, l'île, et surtout… votre réponse.",
      countdown: "jours avant le grand jour",
      cta: "Répondre à l'invitation",
      ctaDone: "Voir / modifier ma réponse",
    },
    rsvp: {
      title: "Votre réponse",
      deadline: "Vous pouvez modifier votre réponse à tout moment jusqu'au",
      closed: "La date limite de réponse est passée. Contactez-nous directement pour tout changement.",
      attending: "Est-ce que vous venez ?",
      yes: "Oui, on sera là ! 🎉",
      no: "Non, on ne pourra pas venir 😢",
      contact: "Vos coordonnées",
      contactHint: "On s'en sert uniquement pour les infos du mariage. Complétez ce qui manque, corrigez si besoin.",
      emailLabel: "Email",
      phoneLabel: "Téléphone (WhatsApp)",
      contactRequired: "Merci d'indiquer au moins un email ou un téléphone.",
      participants: "Qui vient ?",
      addParticipant: "Ajouter une personne",
      firstName: "Prénom",
      lastName: "Nom",
      adult: "Adulte",
      child: "Enfant",
      age: "Âge",
      diet: "Alimentation",
      dietNone: "Rien à signaler",
      dietVeg: "Végétarien / végétalien",
      dietAllergy: "Allergie grave",
      dietNote: "Précisez l'allergie",
      events: "Présent·e à…",
      logistics: "Vos dates (pour nous aider à nous organiser)",
      logisticsHint: "Ces dates nous donnent juste une idée d'ensemble — elles n'engagent personne, ni vous ni nous, et ne valent pas réservation. Vous pourrez les modifier plus tard.",
      arrival: "Date d'arrivée",
      departure: "Date de départ",
      transport: "Comment venez-vous ?",
      tPlane: "Avion (via Athènes)",
      tFerry: "Ferry",
      tCar: "Voiture + bateau-taxi",
      tOther: "Autre / pas encore décidé",
      accommodation: "Où logez-vous ?",
      aBooked: "Hébergement réservé",
      aSearching: "En recherche",
      aHosted: "Logé·e par les mariés / famille",
      aUnknown: "Pas encore décidé",
      notes: "Un mot pour nous ? (optionnel)",
      save: "Enregistrer ma réponse",
      saved: "Réponse enregistrée, merci ! Vous pouvez revenir la modifier quand vous voulez.",
      noMsg: "On est tristes, mais merci de nous avoir prévenus. Si vos plans changent, revenez modifier votre réponse !",
    },
    programme: {
      title: "Le programme",
      intro: "Quatre jours de fête. Les lieux et horaires précis seront révélés ici quelques semaines avant — gardez l'œil ouvert.",
      detailsSoon: "Lieu & détails bientôt",
    },
    news: {
      title: "Actualités",
      intro: "Les dernières nouvelles des préparatifs, nos rappels et quelques photos.",
      wallTitle: "Le mur de photos",
      wallIntro: "Partagez vos photos ! On y jette un œil avant publication, histoire d'éviter les surprises.",
      wallEmpty: "Aucune photo pour l'instant — lancez-vous, soyez les premiers !",
      addPhoto: "Choisir une photo",
      caption: "Une légende ? (optionnel)",
      submit: "Envoyer la photo",
      submitted: "Merci ! Votre photo apparaîtra dès qu'on l'aura validée.",
    },
    contact: {
      title: "Une question ?",
      intro: "Écrivez-nous, on répond vite. Et quelques semaines avant le mariage, le lien du groupe WhatsApp apparaîtra ici.",
      name: "Votre nom",
      email: "Votre email",
      message: "Votre message",
      send: "Envoyer",
      sent: "Message envoyé, merci ! On revient vers vous rapidement.",
      reachUs: "Nous joindre directement",
      whatsappSoon: "Le groupe WhatsApp « sur place » ouvrira quelques semaines avant le mariage.",
      whatsappJoin: "Rejoindre le groupe WhatsApp",
    },
    landing: {
      private: "Ce site est privé : il est réservé aux invités du mariage. Utilisez le lien personnel reçu par email ou WhatsApp — ou saisissez le code qui figure sur votre invitation.",
      codeLabel: "Code d'invitation",
      enter: "Entrer",
      unknownCode: "Code inconnu — vérifiez votre invitation ou écrivez-nous.",
      organisers: "Espace organisateurs",
      unknownTitle: "Lien inconnu",
      unknownBody: "Ce lien d'invitation n'est pas valide. Vérifiez le message reçu ou contactez-nous.",
      back: "Retour",
    },
    errors: {
      check: "Impossible de vérifier le code pour l'instant. Réessayez dans un instant.",
      save: "L'enregistrement a échoué. Vérifiez votre connexion et réessayez.",
      photo: "L'envoi a échoué. Réessayez avec une photo plus légère.",
      message: "L'envoi a échoué. Réessayez dans un instant.",
    },
    common: {
      until: "jusqu'au",
      backHome: "Retour à l'accueil",
      loading: "Chargement…",
    },
  },

  en: {
    nav: {
      home: "Home",
      rsvp: "RSVP",
      programme: "Programme",
      spetses: "Spetses",
      story: "Our story",
      news: "News",
      contact: "Contact",
    },
    home: {
      welcome: "Welcome",
      intro: "We're getting married in Spetses, and we want you there! Everything you need is here: the programme, the island, and above all… your answer.",
      countdown: "days until the big day",
      cta: "Reply to the invitation",
      ctaDone: "View / edit my reply",
    },
    rsvp: {
      title: "Your reply",
      deadline: "You can edit your reply anytime until",
      closed: "The reply deadline has passed. Contact us directly for any change.",
      attending: "Are you coming?",
      yes: "Yes, we'll be there! 🎉",
      no: "No, we can't make it 😢",
      contact: "Your contact details",
      contactHint: "Used only for wedding updates. Fill in what's missing, correct anything that's wrong.",
      emailLabel: "Email",
      phoneLabel: "Phone (WhatsApp)",
      contactRequired: "Please give us at least an email or a phone number.",
      participants: "Who's coming?",
      addParticipant: "Add a person",
      firstName: "First name",
      lastName: "Last name",
      adult: "Adult",
      child: "Child",
      age: "Age",
      diet: "Diet",
      dietNone: "Nothing to report",
      dietVeg: "Vegetarian / vegan",
      dietAllergy: "Serious allergy",
      dietNote: "Specify the allergy",
      events: "Attending…",
      logistics: "Your dates (to help us organise)",
      logisticsHint: "These dates just give us a general picture — they commit no one, and are not a booking. You can change them later.",
      arrival: "Arrival date",
      departure: "Departure date",
      transport: "How are you coming?",
      tPlane: "Plane (via Athens)",
      tFerry: "Ferry",
      tCar: "Car + water taxi",
      tOther: "Other / not decided yet",
      accommodation: "Where are you staying?",
      aBooked: "Accommodation booked",
      aSearching: "Still looking",
      aHosted: "Hosted by the couple / family",
      aUnknown: "Not decided yet",
      notes: "A word for us? (optional)",
      save: "Save my reply",
      saved: "Reply saved, thank you! You can come back and edit it anytime.",
      noMsg: "We're sad, but thanks for letting us know. If your plans change, come back and edit your reply!",
    },
    programme: {
      title: "The programme",
      intro: "Four days of celebration. Exact venues and times will be revealed here a few weeks before — stay tuned.",
      detailsSoon: "Venue & details soon",
    },
    news: {
      title: "News",
      intro: "The latest from the preparations, our reminders and a few photos.",
      wallTitle: "The photo wall",
      wallIntro: "Share your photos! We take a quick look before publishing, just to avoid surprises.",
      wallEmpty: "No photos yet — go on, be the first!",
      addPhoto: "Choose a photo",
      caption: "A caption? (optional)",
      submit: "Send the photo",
      submitted: "Thank you! Your photo will appear as soon as we've approved it.",
    },
    contact: {
      title: "A question?",
      intro: "Write to us, we answer fast. A few weeks before the wedding, the WhatsApp group link will appear here.",
      name: "Your name",
      email: "Your email",
      message: "Your message",
      send: "Send",
      sent: "Message sent, thank you! We'll get back to you soon.",
      reachUs: "Reach us directly",
      whatsappSoon: "The on-site WhatsApp group will open a few weeks before the wedding.",
      whatsappJoin: "Join the WhatsApp group",
    },
    landing: {
      private: "This site is private: it is reserved for the wedding guests. Use the personal link you received by email or WhatsApp — or enter the code shown on your invitation.",
      codeLabel: "Invitation code",
      enter: "Enter",
      unknownCode: "Unknown code — check your invitation or write to us.",
      organisers: "Organisers' area",
      unknownTitle: "Unknown link",
      unknownBody: "This invitation link is not valid. Check the message you received, or contact us.",
      back: "Back",
    },
    errors: {
      check: "We can't check the code right now. Please try again in a moment.",
      save: "Saving failed. Check your connection and try again.",
      photo: "Upload failed. Try again with a smaller photo.",
      message: "Sending failed. Please try again in a moment.",
    },
    common: {
      until: "until",
      backHome: "Back to home",
      loading: "Loading…",
    },
  },

  el: {
    nav: {
      home: "Αρχική",
      rsvp: "RSVP",
      programme: "Πρόγραμμα",
      spetses: "Σπέτσες",
      story: "Η ιστορία μας",
      news: "Νέα",
      contact: "Επικοινωνία",
    },
    home: {
      welcome: "Καλώς ήρθατε",
      intro: "Παντρευόμαστε στις Σπέτσες και σας θέλουμε μαζί μας! Εδώ θα βρείτε όλα όσα χρειάζεστε: το πρόγραμμα, το νησί και κυρίως… την απάντησή σας.",
      countdown: "ημέρες μέχρι τη μεγάλη μέρα",
      cta: "Απαντήστε στην πρόσκληση",
      ctaDone: "Δείτε / αλλάξτε την απάντησή μου",
    },
    rsvp: {
      title: "Η απάντησή σας",
      deadline: "Μπορείτε να αλλάξετε την απάντησή σας οποτεδήποτε μέχρι",
      closed: "Η προθεσμία απάντησης πέρασε. Επικοινωνήστε μαζί μας για οποιαδήποτε αλλαγή.",
      attending: "Θα έρθετε;",
      yes: "Ναι, θα είμαστε εκεί! 🎉",
      no: "Όχι, δεν θα τα καταφέρουμε 😢",
      contact: "Τα στοιχεία σας",
      contactHint: "Τα χρησιμοποιούμε μόνο για νέα του γάμου. Συμπληρώστε ό,τι λείπει και διορθώστε ό,τι χρειάζεται.",
      emailLabel: "Email",
      phoneLabel: "Τηλέφωνο (WhatsApp)",
      contactRequired: "Δώστε μας τουλάχιστον ένα email ή ένα τηλέφωνο.",
      participants: "Ποιοι έρχονται;",
      addParticipant: "Προσθήκη ατόμου",
      firstName: "Όνομα",
      lastName: "Επώνυμο",
      adult: "Ενήλικας",
      child: "Παιδί",
      age: "Ηλικία",
      diet: "Διατροφή",
      dietNone: "Τίποτα ιδιαίτερο",
      dietVeg: "Χορτοφάγος / vegan",
      dietAllergy: "Σοβαρή αλλεργία",
      dietNote: "Περιγράψτε την αλλεργία",
      events: "Παρών/ούσα σε…",
      logistics: "Οι ημερομηνίες σας (για να οργανωθούμε)",
      logisticsHint: "Οι ημερομηνίες μας δίνουν απλώς μια γενική εικόνα — δεν δεσμεύουν κανέναν και δεν αποτελούν κράτηση. Μπορείτε να τις αλλάξετε αργότερα.",
      arrival: "Ημερομηνία άφιξης",
      departure: "Ημερομηνία αναχώρησης",
      transport: "Πώς θα έρθετε;",
      tPlane: "Αεροπλάνο (μέσω Αθήνας)",
      tFerry: "Πλοίο",
      tCar: "Αυτοκίνητο + θαλάσσιο ταξί",
      tOther: "Άλλο / δεν έχει αποφασιστεί",
      accommodation: "Πού θα μείνετε;",
      aBooked: "Κατάλυμα κλεισμένο",
      aSearching: "Ψάχνουμε ακόμα",
      aHosted: "Φιλοξενούμενοι από το ζευγάρι / την οικογένεια",
      aUnknown: "Δεν έχει αποφασιστεί",
      notes: "Ένα μήνυμα για εμάς; (προαιρετικό)",
      save: "Αποθήκευση απάντησης",
      saved: "Η απάντηση αποθηκεύτηκε, ευχαριστούμε! Μπορείτε να την αλλάξετε όποτε θέλετε.",
      noMsg: "Λυπόμαστε, αλλά ευχαριστούμε που μας ενημερώσατε. Αν αλλάξουν τα σχέδιά σας, ελάτε να αλλάξετε την απάντησή σας!",
    },
    programme: {
      title: "Το πρόγραμμα",
      intro: "Τέσσερις ημέρες γιορτής. Οι ακριβείς τοποθεσίες και ώρες θα ανακοινωθούν εδώ λίγες εβδομάδες πριν.",
      detailsSoon: "Τοποθεσία & λεπτομέρειες σύντομα",
    },
    news: {
      title: "Νέα",
      intro: "Τα τελευταία νέα των προετοιμασιών, υπενθυμίσεις και μερικές φωτογραφίες.",
      wallTitle: "Ο τοίχος φωτογραφιών",
      wallIntro: "Μοιραστείτε τις φωτογραφίες σας! Τις βλέπουμε πριν τη δημοσίευση, για να αποφύγουμε τις εκπλήξεις.",
      wallEmpty: "Καμία φωτογραφία ακόμα — γίνετε οι πρώτοι!",
      addPhoto: "Επιλέξτε φωτογραφία",
      caption: "Λεζάντα; (προαιρετικό)",
      submit: "Αποστολή φωτογραφίας",
      submitted: "Ευχαριστούμε! Η φωτογραφία σας θα εμφανιστεί μόλις εγκριθεί.",
    },
    contact: {
      title: "Έχετε ερωτήσεις;",
      intro: "Γράψτε μας, απαντάμε γρήγορα. Λίγες εβδομάδες πριν τον γάμο, εδώ θα εμφανιστεί ο σύνδεσμος της ομάδας WhatsApp.",
      name: "Το όνομά σας",
      email: "Το email σας",
      message: "Το μήνυμά σας",
      send: "Αποστολή",
      sent: "Το μήνυμα στάλθηκε, ευχαριστούμε! Θα σας απαντήσουμε σύντομα.",
      reachUs: "Επικοινωνήστε απευθείας",
      whatsappSoon: "Η ομάδα WhatsApp θα ανοίξει λίγες εβδομάδες πριν τον γάμο.",
      whatsappJoin: "Μπείτε στην ομάδα WhatsApp",
    },
    landing: {
      private: "Αυτή η ιστοσελίδα είναι ιδιωτική: προορίζεται μόνο για τους καλεσμένους του γάμου. Χρησιμοποιήστε τον προσωπικό σύνδεσμο που λάβατε με email ή WhatsApp — ή πληκτρολογήστε τον κωδικό της πρόσκλησής σας.",
      codeLabel: "Κωδικός πρόσκλησης",
      enter: "Είσοδος",
      unknownCode: "Άγνωστος κωδικός — ελέγξτε την πρόσκλησή σας ή γράψτε μας.",
      organisers: "Χώρος διοργανωτών",
      unknownTitle: "Άγνωστος σύνδεσμος",
      unknownBody: "Αυτός ο σύνδεσμος πρόσκλησης δεν είναι έγκυρος. Ελέγξτε το μήνυμα που λάβατε ή επικοινωνήστε μαζί μας.",
      back: "Πίσω",
    },
    errors: {
      check: "Δεν μπορούμε να ελέγξουμε τον κωδικό αυτή τη στιγμή. Δοκιμάστε ξανά σε λίγο.",
      save: "Η αποθήκευση απέτυχε. Ελέγξτε τη σύνδεσή σας και δοκιμάστε ξανά.",
      photo: "Η αποστολή απέτυχε. Δοκιμάστε με μικρότερη φωτογραφία.",
      message: "Η αποστολή απέτυχε. Δοκιμάστε ξανά σε λίγο.",
    },
    common: {
      until: "μέχρι",
      backHome: "Πίσω στην αρχική",
      loading: "Φόρτωση…",
    },
  },
};
